import { faker } from "@faker-js/faker";
export const fakeDataLastOperationSidebar = [
  {
    id: 1,
    nombre: faker.name.fullName(),
    producto: faker.commerce.productName(),
    monto: faker.commerce.price(),
    pago: "Bs",
  },
  {
    id: 2,
    nombre: faker.name.fullName(),
    producto: faker.commerce.productName(),
    monto: faker.commerce.price(),
    pago: "Dolares",
  },
  {
    id: 3,
    nombre: faker.name.fullName(),
    producto: faker.commerce.productName(),
    monto: faker.commerce.price(),
    pago: "Zelle",
  },
  {
    id: 4,
    nombre: faker.name.fullName(),
    producto: faker.commerce.productName(),
    monto: faker.commerce.price(),
    pago: "Pago Movil",
  },
  {
    id: 5,
    nombre: faker.name.fullName(),
    producto: faker.commerce.productName(),
    monto: faker.commerce.price(),
    pago: "Dolares",
  },
  {
    id: 6,
    nombre: faker.name.fullName(),
    producto: faker.commerce.productName(),
    monto: faker.commerce.price(),
    pago: "Bs",
  },
  {
    id: 7,
    nombre: faker.name.fullName(),
    producto: faker.commerce.productName(),
    monto: faker.commerce.price(),
    pago: "Bs",
  },
  {
    id: 8,
    nombre: faker.name.fullName(),
    producto: faker.commerce.productName(),
    monto: faker.commerce.price(),
    pago: "Dolares",
  },
  {
    id: 9,
    nombre: faker.name.fullName(),
    producto: faker.commerce.productName(),
    monto: faker.commerce.price(),
    pago: "Punto de venta",
  },
  {
    id: 10,
    nombre: faker.name.fullName(),
    producto: faker.commerce.productName(),
    monto: faker.commerce.price(),
    pago: "Bs",
  },
];
